export const jobPositionsList = [
  { label: "Engenheiro Civil", value: "civil_engineer" },
  { label: "Eletricista", value: "electrician" },
  { label: "Soldador", value: "welder" },
  { label: "Operador de Máquinas", value: "machine_operator" },
  { label: "Técnico de Segurança do Trabalho", value: "safety_technician" },
  { label: "Pedreiro", value: "bricklayer" },
  { label: "Encanador", value: "plumber" },
  { label: "Carpinteiro", value: "carpenter" },
  { label: "Motorista", value: "driver" },
  { label: "Almoxarife", value: "storekeeper" },
  { label: "Técnico de Manutenção", value: "maintenance_technician" },
  { label: "Analista de Qualidade", value: "quality_analyst" },
  { label: "Gerente de Produção", value: "production_manager" },
  { label: "Operador de Empilhadeira", value: "forklift_operator" },
  { label: "Assistente Administrativo", value: "administrative_assistant" },
  { label: "Supervisor de Operações", value: "operations_supervisor" },
  { label: "Auxiliar de Limpeza", value: "cleaning_assistant" },
  { label: "Enfermeiro", value: "nurse" },
  { label: "Analista de Logística", value: "logistics_analyst" },
  { label: "Gerente de Projetos", value: "project_manager" },
];
